package ru.mulledwine.shifts.data.local

import android.content.Context
import android.content.SharedPreferences
import androidx.lifecycle.LiveData
import androidx.preference.PreferenceManager
import ru.mulledwine.shifts.App
import ru.mulledwine.shifts.data.delegates.PrefDelegate
import ru.mulledwine.shifts.data.delegates.PrefLiveDelegate

class PrefManager(context: Context) {

    companion object {
        const val delimiter = "%%%"
    }

    internal val preferences: SharedPreferences by lazy {
        PreferenceManager.getDefaultSharedPreferences(context)
    }

    var isCalendarGenerated by PrefDelegate(false)

    private var shownHints by PrefDelegate("")

    val shownHintsLive: LiveData<String> by PrefLiveDelegate ("shownHints", "", preferences)

    fun getShownHints(): List<String> = shownHints.split(delimiter)

    fun addHintToShown(id: String) {
        shownHints = "$shownHints$delimiter$id"
    }

    fun resetHints() {
        shownHints = ""
    }

}